"use client";

// One candidate on the avatar. The body is whatever its motion source says: a motion-capture
// clip baked into the asset, or a track generated by a model. Nothing here poses the body by
// rule any more; the hand-written body language was deleted on 2026-09-19. What is left is
// playback, foot grounding and the mouth (see lib/motion.ts).

import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { groundOffset, speechFace } from "@/lib/motion";
import type { MotionPolicy } from "@/lib/types";

const FADE = 0.35;
const TOES = ["LeftToeBase", "RightToeBase"];

interface Props {
  policy: MotionPolicy;
  avatar: string;
  /** Speech loudness 0..1 right now; 0 when nothing plays. */
  level: () => number;
  /** Whether the shared audio is playing. */
  playing: boolean;
  seed: number;
  label: string;
  onClips?: (names: string[]) => void;
}

export default function MotionStage({ policy, avatar, level, playing, seed, label, onClips }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "failed" | "unsupported">("loading");
  const playingRef = useRef(playing);
  const policyRef = useRef(policy);
  useEffect(() => { playingRef.current = playing; }, [playing]);
  useEffect(() => { policyRef.current = policy; }, [policy]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    let disposed = false;
    const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(2, window.devicePixelRatio));
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(32, 1, 0.1, 40);
    camera.position.set(0, 1.34, 4.35);
    camera.lookAt(0, 1.02, 0);
    scene.add(new THREE.AmbientLight(0xd5f0ff, 0.85));
    const key = new THREE.DirectionalLight(0xd6f5ff, 1.5); key.position.set(-2, 4, 5); scene.add(key);
    const warm = new THREE.DirectionalLight(0xd7c2a0, 1.1); warm.position.set(3, 1, 2); scene.add(warm);
    const rim = new THREE.DirectionalLight(0x9fd8e8, 1.4); rim.position.set(0, 2.5, -4); scene.add(rim);
    // The contact shadow gets its own nearly-overhead light. The key at (-2, 4, 5) throws the
    // hips' shadow 0.58 to the right and 1.45 behind the feet: correct, and useless as a
    // contact cue, which is half of why the figure read as floating.
    const contact = new THREE.DirectionalLight(0xffffff, 0.18);
    contact.position.set(0.25, 6, 0.6);
    contact.castShadow = true;
    contact.shadow.mapSize.set(1024, 1024);
    contact.shadow.camera.top = 2; contact.shadow.camera.bottom = -2;
    contact.shadow.camera.left = -1.5; contact.shadow.camera.right = 1.5;
    contact.shadow.camera.near = 1; contact.shadow.camera.far = 9;
    contact.shadow.bias = -0.002;
    scene.add(contact, contact.target);
    const ground = new THREE.Mesh(new THREE.PlaneGeometry(24, 24), new THREE.ShadowMaterial({ opacity: 0.5 }));
    ground.rotation.x = -Math.PI / 2;
    ground.receiveShadow = true;
    scene.add(ground);

    const morphs: { influences: number[]; index: Record<string, number> }[] = [];
    const toes: THREE.Object3D[] = [];
    let mixer: THREE.AnimationMixer | null = null;
    let action: THREE.AnimationAction | null = null;
    let idleAction: THREE.AnimationAction | null = null;
    let speakAction: THREE.AnimationAction | null = null;
    let speakingNow = false;
    let time = seed % 1000;
    let raf = 0;
    const clock = new THREE.Clock();
    const foot = new THREE.Vector3();

    const play = (next: THREE.AnimationAction | null) => {
      if (!next || next === action) return;
      next.reset(); next.play();
      if (action) action.crossFadeTo(next, FADE, false);
      action = next;
    };
    const resize = () => {
      const { width, height } = canvas.getBoundingClientRect();
      if (!width || !height) return;
      renderer.setSize(width, height, false);
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
    };
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    new GLTFLoader().loadAsync(avatar).then((gltf) => {
      if (disposed) return;
      const root = gltf.scene;
      root.traverse((node) => {
        const mesh = node as THREE.Mesh;
        if (mesh.isMesh) mesh.castShadow = true;
        if (mesh.isMesh && mesh.morphTargetDictionary && mesh.morphTargetInfluences) morphs.push({ influences: mesh.morphTargetInfluences, index: mesh.morphTargetDictionary });
      });
      onClips?.(gltf.animations.map((a) => a.name));
      for (const n of TOES) { const b = root.getObjectByName(n); if (b) toes.push(b); }

      const p = policyRef.current;
      const find = (name: string) => gltf.animations.find((a) => a.name === name);
      if (p.source === "generated") {
        // No generated track is wired in yet; say so rather than quietly showing something else.
        setStatus("unsupported");
        return;
      }
      const idle = find("Breathing Idle") ?? find("Idle");
      const speak = p.clip ? find(p.clip) : undefined;
      if (!gltf.animations.length || (!idle && !speak)) { setStatus("failed"); return; }
      mixer = new THREE.AnimationMixer(root);
      if (idle) idleAction = mixer.clipAction(idle).setLoop(THREE.LoopRepeat, Infinity);
      if (speak) speakAction = mixer.clipAction(speak).setLoop(THREE.LoopRepeat, Infinity);
      play(idleAction ?? speakAction);

      scene.add(root);
      if (process.env.NODE_ENV !== "production") {
        const w = window as unknown as { __arena?: Record<string, unknown> };
        w.__arena = w.__arena ?? {};
        w.__arena[label] = {
          policy: p, root, scene,
          footY: () => TOES.map((n) => {
            const bone = root.getObjectByName(n);
            if (!bone) return [n, null] as const;
            const v = new THREE.Vector3(); bone.getWorldPosition(v);
            return [n, Number(v.y.toFixed(4))] as const;
          }),
        };
      }
      setStatus("ready");
      resize();

      const tick = () => {
        raf = requestAnimationFrame(tick);
        const delta = Math.min(0.1, clock.getDelta());
        time += delta;
        const want = playingRef.current;
        if (want !== speakingNow) { speakingNow = want; play(want ? speakAction ?? idleAction : idleAction ?? speakAction); }
        mixer?.update(delta);

        // Foot grounding. The clips were retargeted with the hips' translation locked, so any
        // leg flexion lifts the feet off the floor. Measure from a zero offset, then apply.
        if (toes.length) {
          root.position.y = 0;
          root.updateWorldMatrix(true, true);
          root.position.y = groundOffset(toes.map((t) => { t.getWorldPosition(foot); return foot.y; }));
        }

        const face = speechFace(want ? level() : 0, time);
        for (const s of morphs) for (const [name, value] of Object.entries(face)) { const i = s.index[name]; if (i !== undefined) s.influences[i] = value; }
        renderer.render(scene, camera);
      };
      raf = requestAnimationFrame(tick);
    }).catch(() => { if (!disposed) setStatus("failed"); });

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      observer.disconnect();
      renderer.dispose();
    };
  }, [policy.id, avatar, seed]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="relative rounded-xl overflow-hidden border border-gray-200 bg-[#0d1117]" style={{ aspectRatio: "3 / 4" }}>
      <canvas ref={canvasRef} className="w-full h-full block" />
      <div className="absolute top-2 left-3 text-white/90 font-mono text-lg font-semibold">{label}</div>
      {status !== "ready" && (
        <div className="absolute inset-0 grid place-items-center text-center text-sm text-white/70 px-6">
          {status === "loading" ? "loading avatar…"
            : status === "unsupported" ? "generated motion is not wired in yet"
            : "avatar failed to load (bash scripts/import-avatar.sh)"}
        </div>
      )}
    </div>
  );
}
