// The candidate space of the motion arena (docs/protocol.md §1) and the line bank.
// Policies are a small discrete design over the two things the site can do today: play a
// Mixamo clip underneath, and run the procedural rules on top at some amplitude. A learned
// policy (source "model") joins the same table when a co-speech model produces tracks.

import type { MotionPolicy } from "./types";

// "Telling A Secret" was dropped on 2026-09-19: it is a conspiratorial hunch, weight on one
// foot and a hand cupped at the mouth, which reads as the body floating and is wrong for a
// digital human answering a question. "Lengthy Head Nod" gestures with its hands while
// nodding, so it stays as the second thing a speaking body can do; the arena ranks the two.
export const SPEAKING_CLIPS = ["Talking", "Lengthy Head Nod"] as const;
/** The clips the served asset carries; the renderer reports which it actually found. */
export const KNOWN_CLIPS = ["Breathing Idle", "Head Nod Yes", "Idle", "Lengthy Head Nod", "Shrugging", "Talking", "Telling A Secret", "Thoughtful Head Nod", "Waving"] as const;

/**
 * The candidates the arena can draw. Until 2026-09-19 this was a grid of hand-written
 * amplitude knobs over the procedural body, 27 of 47 policies being variants of a guess. The
 * knobs are gone. A candidate is a motion source: one of the avatar's motion-capture clips,
 * or a track generated by a model, which `registerGenerated` adds as the models land.
 */
const GENERATED: MotionPolicy[] = [
  // Motion generated by EMAGE from the round's own audio and retargeted onto this rig
  // (motion/build_tracks.py). A round can only offer it when a track exists for that clip,
  // which the sampler checks, because generated motion is tied to the audio it came from.
  { id: "model:emage", name: "EMAGE (generated)", source: "generated", clip: null, model: "emage" },
];

/** The site's current behaviour: the Talking capture. */
export const SITE_DEFAULT: MotionPolicy = { id: "clip:Talking", name: "Talking (motion capture)", source: "clip", clip: "Talking" };

/** Add another generated candidate, so a second model can be ranked against the first. */
export function registerGenerated(policy: Omit<MotionPolicy, "source">): void {
  if (!GENERATED.some((p) => p.id === policy.id)) GENERATED.push({ ...policy, source: "generated" });
}

/** Where a generated track lives for a given clip: one file per audio, per model. */
export function trackPath(audioPath: string, model: string): string {
  const stem = audioPath.split("/").pop()?.replace(/\.wav$/, "") ?? "";
  return `/motion/${stem}.${model}.json`;
}

/** Where a profile's retargeted track is served from: one file per profile. */
export function profileTrackPath(profileId: string): string {
  return `/motion/profile-${profileId}.track.json`;
}

export function designSpace(): MotionPolicy[] {
  const clips: MotionPolicy[] = SPEAKING_CLIPS.map((clip) => ({
    id: `clip:${clip}`, name: `${clip} (motion capture)`, source: "clip", clip,
  }));
  return [...clips, ...GENERATED];
}

export function policyById(id: string): MotionPolicy | undefined {
  return designSpace().find((p) => p.id === id);
}

/**
 * Two distinct candidates, drawn with inverse-frequency weighting over how often each has
 * already been served, so the table fills evenly instead of by chance. The pool defaults to
 * the design space; the arena route passes profiles merged in (they are data, not code).
 */
export function samplePair(
  served: Map<string, number>,
  rng: () => number = Math.random,
  usable: (p: MotionPolicy) => boolean = () => true,
  pool: MotionPolicy[] = designSpace(),
): [MotionPolicy, MotionPolicy] {
  const candidates = pool.filter(usable);
  const weight = (p: MotionPolicy) => 1 / (1 + (served.get(p.id) ?? 0));
  const draw = (exclude?: MotionPolicy): MotionPolicy => {
    const items = candidates.filter((p) => p.id !== exclude?.id);
    const total = items.reduce((s, p) => s + weight(p), 0);
    let r = rng() * total;
    for (const p of items) { r -= weight(p); if (r <= 0) return p; }
    return items[items.length - 1];
  };
  const a = draw();
  return [a, draw(a)];
}

export interface LineCategory { id: string; label: string; lines: string[] }

/** Lines the digital human actually says: the same kinds of sentence the voice arena uses. */
export const LINE_BANK: LineCategory[] = [
  { id: "greeting", label: "Greeting", lines: [
    "Hi, welcome in. I'm glad you found your way here. Take a look around, and ask me anything that catches your eye.",
    "Hey, good to see you. Come in, make yourself comfortable.",
    "Welcome. This is the space I built. Feel free to wander, and I'll be right here if you have questions.",
    "Oh, hello! I wasn't expecting anyone this early. Come on in.",
  ] },
  { id: "answer", label: "Answering a question", lines: [
    "So you're asking which fix I'd try first. Honestly, I'd check the learning rate before anything else, because that's where it usually goes wrong.",
    "That flat accuracy while the loss keeps dropping usually means the model is getting more confident about the wrong answers.",
    "Doubling the learning rate mostly makes training bounce around, and sometimes it just blows up. I'd halve it and watch the curve.",
    "Good question. Short answer, yes, but it depends on the data, and I've been burned by that before.",
  ] },
  { id: "explaining", label: "Explaining", lines: [
    "Attention lets every token look at every other token at the same time. That is the whole trick, and everything else is bookkeeping.",
    "There are three parts to this: the intuition, the math, and one worked example. Let's start with the intuition.",
    "Think of the mirror as a sketch that decides where the world breaks. Your lines become the cracks, and the cracks become the doorway.",
  ] },
  { id: "thinking", label: "Thinking aloud", lines: [
    "Hmm, that's a good one. Let me think about it for a second. I believe the short answer is yes, but it depends on the data.",
    "Okay, so there are two ways to look at this, and I'm not sure which one you're asking about.",
    "Right, so, if I remember correctly, the paper reported that, but I'd want to double check the setup.",
  ] },
  { id: "delight", label: "Delighted", lines: [
    "Oh, this is one of my favourite topics! There's something so satisfying about watching all these pieces click into place.",
    "You drew that? That's wonderful. Look at how the world grew out of three lines.",
    "Yes! That is exactly the question I was hoping you'd ask.",
  ] },
];

export function pickLine(category: string, rng: () => number = Math.random): { category: string; text: string } {
  const pool = category === "any" ? LINE_BANK : LINE_BANK.filter((c) => c.id === category);
  const cat = pool[Math.floor(rng() * pool.length)] ?? LINE_BANK[0];
  return { category: cat.id, text: cat.lines[Math.floor(rng() * cat.lines.length)] };
}
